### PR TITLE
#5 #6 #20 #21 Access to local files + Upload image to database + Init…

### PR DESCRIPTION
**Pull request by NabilahRouf**
…ial profile page layout

### CODE REVIEW

**Review by liborioc1 — COMMENTED** [review]
#20 the progress bar should not appear in the header. Also the profile page design should include followers and following count. Still work to be done.

**Comment by NabilahRouf** [comment]
@liborioc1 Thanks for letting me know, I'll make the progress bar appear below the header. I'll also add in the follower and following count once these values are set in the database.

**Comment by liborioc1** [comment]
> @liborioc1 Thanks for letting me know, I'll make the progress bar appear below the header. I'll also add in the follower and following count once these values are set in the database.

Okay @melsagh we should get this going so that we can continue to progress and update the UI.

**Review by Salma-Elmahallawy — APPROVED** [review]
The header should also be added to the home page because currently there is only an upload button. Everything else seems good.

**Review by liborioc1 — APPROVED** [review]

**Comment by melsagh** [comment]
> > @liborioc1 Thanks for letting me know, I'll make the progress bar appear below the header. I'll also add in the follower and following count once these values are set in the database.
> 
> Okay @melsagh we should get this going so that we can continue to progress and update the UI.

Noted. Currently in progress!

**Pull request merged**
