### PR TITLE
#7 #23 #31 #66 #67 Modified feed to remove gray bar if no posts are l…

### PR DESCRIPTION
**Pull request by TarekElDick**
…oaded, fixed comments showing the posts timestamp and did some preliminary posts layout modifications

### CODE REVIEW

**Review by Salma-Elmahallawy — APPROVED** [review]
Looks good Tarek! @NabilahRouf please check the fonts he used when you update too :)

**Review by NabilahRouf — APPROVED** [review]

**Comment by NabilahRouf** [comment]
@Salma-Elmahallawy Yes, I'll review font sizes/styles as well as spacing for the post layout!

**Comment by Salma-Elmahallawy** [comment]
> @Salma-Elmahallawy Yes, I'll review font sizes/styles as well as spacing for the post layout!

Great Thanks!

**Review by melsagh — APPROVED** [review]
loving the proactivity!

**Review by liborioc1 — APPROVED** [review]
@NabilahRouf when you look into making additional adjustments to the layout make sure to handle different pic sizes it seems to dynamically grow but can still cause issues and its not very consistent

**Comment by NabilahRouf** [comment]
> @NabilahRouf when you look into making additional adjustments to the layout make sure to handle different pic sizes it seems to dynamically grow but can still cause issues and its not very consistent

I'll look into it!

**Pull request merged**
